<a href="https://colab.research.google.com/github/Amritpal-nitj/BreastCancerDetectionModel/blob/main/creatingvariableintensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#creating variable


**The Variable() constructor requires an initial value for the variable, which can be a Tensor of any type and shape. This initial value defines the type and shape of the variable. After construction, the type and shape of the variable are fixed. The value can be changed using one of the assign methods.**


In [8]:
import tensorflow as tf

CREATE TENSOR

In [9]:
tf_Var=tf.Variable([1,2,3,4])
tf_Var

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [10]:
tf_Var.name   #name assigned to variable by tensorflow

'Variable:0'

In [11]:
tf_Var.dtype

tf.int32

In [12]:
tf_Var.shape

TensorShape([4])

In [22]:
tf_Var.numpy()  #to access value of tensor

array([1, 2, 3, 4], dtype=int32)

# *create tensorflow using Integer, Float,String,Bool,Complex number

In [14]:
tf_f=tf.Variable([4.2,5,2])  #Float
tf_f

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([4.2, 5. , 2. ], dtype=float32)>

In [15]:
tf_f.dtype

tf.float32

In [16]:
tf_s=tf.Variable(['a','b','c'])   #string
tf_s

<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'a', b'b', b'c'], dtype=object)>

In [17]:
tf_s.dtype

tf.string

In [18]:
tf_b=tf.Variable([True,False])  #bool
tf_b

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [19]:
tf_b.dtype

tf.bool

In [20]:
tf_c=tf.Variable([1+2j,3+4j])  #complex
tf_c

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([1.+2.j, 3.+4.j])>

In [21]:
tf_c.dtype

tf.complex128

#CREATE TF FROM CONSTANT TENSORFLOW VARIABLE

In [23]:
tf_con=tf.constant([1,2,3,4])
tf_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [24]:
tf_var=tf.Variable(tf_con)  #now we got variable tf from constant tf
tf_var

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

Create tf with different shape

In [28]:
tf_2d=tf.Variable([[1,2],[2,4]])
tf_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [2, 4]], dtype=int32)>

In [29]:
tf_2d=tf.Variable([[1,2],[2,4]],shape=(2,2),dtype=tf.float32)
tf_2d   #we can also provide datatype and shape

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [2., 4.]], dtype=float32)>

In [31]:
tf_1d=tf.Variable([1,2,3,4])
tf_1d

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [33]:
tf_c=tf.reshape(tf_1d,(2,2))  #reshaped
tf_c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#get index of highes value

In [36]:
tf.argmax(tf_c).numpy()  #1st row 1st column :4

array([1, 1])

#viewed/convert as Tensor  
 variable to tensor

In [37]:
tf.convert_to_tensor(tf_c)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

CHANGE OR ASSIGn new value to tensor

In [38]:
tf_1d

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [41]:
tf_1d.assign([4,9,2,8])   #assigned to same memory (replaced)  #we cant change shape and data type of variable

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 9, 2, 8], dtype=int32)>

In [42]:
tf_1d.assign_add([2,1,7,4]) #assigned to another memory and previous elements me add ho jayegi new value

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 6, 10,  9, 12], dtype=int32)>